#!/usr/bin/env python3
import sys
import os
import time
import datetime
import smtplib
import socket
import urllib.request
import dbus

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from systemd import journal

def get_email_settings():
    required_variables = ('FSCK_EMAIL_FROM', 'FSCK_EMAIL_TO', 'FSCK_EMAIL_PASSWORD')
    missing_variables = [name for name in required_variables if not os.environ.get(name)]
    if missing_variables:
        raise RuntimeError(
            'Missing required environment variables: ' + ', '.join(missing_variables) +
            '. See README.md for setup instructions.'
        )

    try:
        smtp_port = int(os.environ.get('FSCK_EMAIL_SMTP_PORT', '587'))
    except ValueError as error:
        raise RuntimeError('FSCK_EMAIL_SMTP_PORT must be an integer') from error

    return {
        'from_address': os.environ['FSCK_EMAIL_FROM'],
        'to_address': os.environ['FSCK_EMAIL_TO'],
        'password': os.environ['FSCK_EMAIL_PASSWORD'],
        'smtp_host': os.environ.get('FSCK_EMAIL_SMTP_HOST', 'smtp.gmail.com'),
        'smtp_port': smtp_port,
    }

def get_ip_address():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80)) #Google DNS IP for connection test
    ip_addr = s.getsockname()[0]
    s.close()
    return(ip_addr)

def main():

    email_settings = get_email_settings()

    # wait for (X) secs to ensure wireless connection is UP and date/time is set correctly after boot. 
    # This is neccessary for script to work via CRON
    # time.sleep(90)
    # set up the SMTP server connection
    try:
        s = smtplib.SMTP(email_settings['smtp_host'], email_settings['smtp_port'])
        s.starttls()
        s.login(email_settings['from_address'], email_settings['password'])
    except:
    	print("Unexpected error during SMTP Connection:", sys.exc_info())
    	raise
    # attempt to invoke start of ntp systemd service so that date/timestamp in email is correct. This is an 
    # alternate approach to just increasing the sleep() time above.
#    try:
#        sysbus = dbus.SystemBus()
#        systemd1 = sysbus.get_object('org.freedesktop.systemd1', '/org/freedesktop/systemd1')
#        manager = dbus.Interface(systemd1, 'org.freedesktop.systemd1.Manager')
#        job = manager.RestartUnit('ntp.service', 'fail')
#        # wait 20 seconds to allow sufficent time for restart of NTP service to occur and for correct system date
#        # to be set.
#        time.sleep(20)
#    except:
#        print("Unexpected error during NTP Service Restart:", sys.exc_info())
#        raise

    # create a MIMEMultipart message required for email
    msg = MIMEMultipart()

    # create a SYSTEMD Journal Reader object
    j = journal.Reader()
    # define scope of Journal entries only to current system boot
    j.this_boot()
    # define scope of Journal entries to only include INFO logs
    j.log_level(journal.LOG_INFO)
    # define scope of Journal entries to only that generated by systemd-fsck daemon
    j.add_match(SYSLOG_IDENTIFIER="systemd-fsck")

    # grab journal entries and write those to a string for email body
    fsck_results_str = ""
    for entry in j:
        fsck_results_str = fsck_results_str + entry['MESSAGE'] + "\n"

    # add IP address to bottom of email body
    fsck_results_str = fsck_results_str + "\nIP Address: " + get_ip_address()

    # print email body string ---- ONLY USED FOR DEBUGGING
    #print(fsck_results_str)

    # setup the parameters of the email message
    msg['From']=email_settings['from_address']
    msg['To']=email_settings['to_address']
    msg['Subject']="FSCK BOOT Results on " + datetime.datetime.now().strftime("%m-%d-%Y %H:%M") + " for host " + socket.gethostbyaddr(socket.gethostname())[0]

    # add to message the the message body string
    msg.attach(MIMEText(fsck_results_str, 'plain'))

    # send the message via the SMTP connection set up earlier.
    s.send_message(msg)
    print("FSCK BOOT Results Email sent successfully")
    # delete the message object now that the message has been sent
    del msg
    # Terminate the SMTP session and close the connection
    s.quit()

if __name__ == '__main__':
    main()
    sys.exit(0)
